### ISSUE TITLE
Custom snippets do not work?

### ISSUE THREAD

**Issue by Globvs** [herbix/hoi4modutilities#1]
This extension is super useful. However, when using custom snippets (specifically https://github.com/MrBlazzar/HOI4-VSCode-User-Snippets/blob/master/hoi4.json) they do not show up when using the extension. Disabling it or turning it off turns it back on, however.

**Comment by Globvs** [comment]
Nevermind, turns out it was a problem on my end. However, how can I make the extension load custom focus icons on my mod?

**Comment by herbix** [comment]
You can refer to this wiki for loading custom icons: https://github.com/herbix/hoi4modutilities/wiki/Reference-custom-sprite_type
