### ISSUE TITLE
Can't understand the step 2

### ISSUE THREAD

**Issue by aesthetically1940s** [herbix/hoi4modutilities#10]
Hi, I can't understand the step 2. Can you wrote more about it, I can't do anything it's so confusing fora non english native speaker and a begginner...

**Comment by herbix** [comment]
Hi @aesthetically1940s,
You can find "install path" setting in VSCode settings:
![image](https://user-images.githubusercontent.com/7110965/91730818-d5c2d400-ebd8-11ea-8cd1-b98884469629.png)
![image](https://user-images.githubusercontent.com/7110965/91730902-ed9a5800-ebd8-11ea-9314-05d649fd1410.png)

**Comment by aesthetically1940s** [comment]
![image](https://user-images.githubusercontent.com/70484870/91731965-dbec8c80-eba7-11ea-8d69-9cb634ae7cc2.png)

The preview still don't work... I'm sorry I'm new in it I can sounds stupid...

**Comment by herbix** [comment]
You need to pair `{` and `}`. It looks like there are several `}`s missing at the end of your script.
I recommend you to type a `}` immediately after typing `{` so it can't be missed.

**Comment by aesthetically1940s** [comment]
Ok, I think I correct everything and now I can't see my focus tree omg this drives me crazy... 

![image](https://user-images.githubusercontent.com/70484870/91737092-e5c5be00-ebae-11ea-9e09-8333dda7e1ce.png)

**Comment by aesthetically1940s** [comment]
![image](https://user-images.githubusercontent.com/70484870/91737773-d135f580-ebaf-11ea-8590-d36e99e2a148.png)
I changed a thing and now it says no fucos tree... I'm very lost...

**Comment by herbix** [comment]
Reason of no focus tree is that in first line "f" of focus_tree is removed.

In line 12 after modifier, an additional "}" is typed so "focus_tree = {" is closed, making it no focus inside the tree.

I recommend you to use syntax tools extension such as cwtools. There will be error markers when you meet such issues.
