### ISSUE TITLE
Preview World Map

### ISSUE THREAD

**Issue by maverick87** [herbix/hoi4modutilities#13]
Getting Terrain ocean etc not defined. But they are defined in the common/terrain folder.

**Comment by herbix** [comment]
The reason of this issue is the extension will only load terrain from `common/terrain/00_terrain.txt`. As a workaround you can just ignore the warning, or put terrain definition into the file.
I will fix this issue in the next release.

**Comment by herbix** [comment]
Fixed in 0.4.4.

**Comment by mrbae05** [comment]
Bug reoccured to me
