### ISSUE TITLE
Red line

### ISSUE THREAD

**Issue by maverick87** [herbix/hoi4modutilities#14]
Getting an red line from South Italy to Australia in Supply Area and Strategic Region in World Map View. It dissapears when zooming in and comes back when zooming out. Checked for adjacencies but couldn't find any.
![2020-11-02](https://user-images.githubusercontent.com/5243534/97874702-ad12a400-1d19-11eb-8f62-7e44a295dd99.png)

**Comment by herbix** [comment]
An adjacency line will only visible when both provinces are visible on map, which is a known issue. There must be a row in `adjacency.txt` that defines the line. In province view, all edges are invisible so it disappears. Currently there's no good way to find out corresponding row in adjacency file.

**Comment by herbix** [comment]
Fixed in 0.4.4. The line won't disappear now. You can debug the start point and end point of the line.
