### ISSUE TITLE
Buildings

### ISSUE THREAD

**Issue by maverick87** [herbix/hoi4modutilities#15]
Not an issue but a sugesstion. Modify buildings position and orientation like in the nudge would be very helpfull. Nudge it self is not very stable. Rgeards

**Comment by herbix** [comment]
Thanks for your suggestion.

However, I don't think it's a good idea to add a feature completely same as Nudge. Nudge is useful enough and I can't easily create a more useful one in short time. To achieve this, there are a lot of things to do such as 3D mesh rendering which are not touched in the extension. I'm not expert of these area too.

Maybe you could write some feedback in Paradox forum to help them improve Nudge.
