### ISSUE TITLE
Preview World Map export [Feature request]

### ISSUE THREAD

**Issue by tombricks** [herbix/hoi4modutilities#17]
An export map which exports the map as an image file.

**Comment by herbix** [comment]
Thanks for your idea. Could you please describe why do you want this feature? I think exporting image is less useful because it is not interactive and won't change when related scripts change.

**Comment by tombricks** [comment]
I was just suggesting it as I presume there is already the code to draw the map in the editor so it would just be a cool feature to export that, so it can be easier to show someone the exact map without having to launch the game or for artwork purposes. Or, if you are discussing a mod, you can show them the whole map with the exact borders and stuff

**Comment by herbix** [comment]
I do have code to draw map in the editor. But only the visible part is drawn. It's easy to export the visible part in editor window. It need more work to export whole map. If you just need the visible part, you can use screenshot tools. So I suppose you want to export whole map, right?

**Comment by tombricks** [comment]
Yes, that would be **based** but I understand if you don't want to.

**Comment by herbix** [comment]
Feature added in 0.4.4.
