### ISSUE TITLE
[BUG]report, help me

### ISSUE THREAD

**Issue by modder23** [herbix/hoi4modutilities#19]
i tried to modding total war mod's techs.

but i can't use preivew.
because,
Error:
UserError: Can't find countrytechtreeview in .

but total war mod got countrytechtreeview files.

plz hellp me

####

i fixed it 

but tech tree's background didnt seen. and line box too

**Comment by herbix** [comment]
Could you try include the file that contains `countrytechtreeview` manually?

Replace the file in the code below and put it in your technology file.
```
#!gui:relative/path/to/guifile.gui
```

**Comment by herbix** [comment]
No update for long time.
