### ISSUE TITLE
tech tree preview not working

### ISSUE THREAD

**Issue by Zapaeryan** [herbix/hoi4modutilities#2]
I've been trying to load the tech tree preview on my custom mod but it's not working or even displaying any of it properly. I've followed all the steps properly but when I load up the preview I get this
![Capture](https://user-images.githubusercontent.com/61558902/84807285-a2ef4380-afcc-11ea-956c-5f3329fc0d56.PNG)

anyone know how I can fix this to get the preview working properly?

**Comment by Zapaeryan** [comment]
so apparently the reason this is happening is that the extension flat out isn't recognizing or loading any of the new .dds files or the new custom folders and techs found in the gui and gfx folders. here's an example of what i'm talking about: 

![Capture](https://user-images.githubusercontent.com/61558902/84811864-1d22c680-afd3-11ea-96a3-f997182ad65a.PNG)

any idea how I can fix this?

**Comment by herbix** [comment]
Hi @Zapaeryan,

But the extension searches files based on your opened folder and HOI4 install folder. Your opened folder is `interface`. So it tried to search `interface/interface/countrytechtreeview.gui` and got nothing. To fix it, you need to open parent folder of `interface`.
![image](https://user-images.githubusercontent.com/7110965/84879895-6734a680-b0be-11ea-950e-ba9f7a436d1e.png)

**Comment by Zapaeryan** [comment]
> Hi @Zapaeryan,
> 
> The extension searches files based on your opened folder and HOI4 install folder. Your opened folder is `interface`. So it tried to search `interface/interface/countrytechtreeview.gui` and got nothing. To fix it, you need to open parent folder of `interface`.
> ![image](https://user-images.githubusercontent.com/7110965/84879895-6734a680-b0be-11ea-950e-ba9f7a436d1e.png)

wow thanks mate, that seemed to do the trick! I really appreciate the help, this will finally let me get into modding hoi4 properly :)
