### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by BrickBotTM** [herbix/hoi4modutilities#20]
I downloaded [it](https://marketplace.visualstudio.com/items?itemName=Chaofan.hoi4modutilities&ssr=false#overview) from here and I x2 click it and this happens.

![image](https://user-images.githubusercontent.com/76825735/103426570-0d8a5a00-4b80-11eb-88cf-cdbe5d45bd34.png)

**Install Log**

12/31/2020 3:50:43 PM - Microsoft VSIX Installer
12/31/2020 3:50:43 PM - -------------------------------------------
12/31/2020 3:50:43 PM - vsixinstaller.exe version:
12/31/2020 3:50:43 PM - 16.8.3036
12/31/2020 3:50:43 PM - -------------------------------------------
12/31/2020 3:50:43 PM - Command line parameters:
12/31/2020 3:50:43 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\ebutz\Downloads\Chaofan.hoi4modutilities-0.4.5.vsix
12/31/2020 3:50:43 PM - -------------------------------------------
12/31/2020 3:50:43 PM - Microsoft VSIX Installer
12/31/2020 3:50:43 PM - -------------------------------------------
12/31/2020 3:50:43 PM - Initializing Install...
12/31/2020 3:50:43 PM - Extension Details...
12/31/2020 3:50:43 PM - 	Identifier         : hoi4modutilities
12/31/2020 3:50:43 PM - 	Name               : HOI4 Mod Utilities
12/31/2020 3:50:43 PM - 	Author             : Chaofan
12/31/2020 3:50:43 PM - 	Version            : 0.4.5
12/31/2020 3:50:43 PM - 	Description        : Utilities for Heart of Iron IV mods developers
12/31/2020 3:50:43 PM - 	Locale             : en-US
12/31/2020 3:50:43 PM - 	MoreInfoURL        : 
12/31/2020 3:50:43 PM - 	InstalledByMSI     : False
12/31/2020 3:50:43 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
12/31/2020 3:50:43 PM - 
12/31/2020 3:50:43 PM - 	SignatureState     : Unsigned
12/31/2020 3:50:43 PM - 	Supported Products : 
12/31/2020 3:50:43 PM - 		Microsoft.VisualStudio.Code
12/31/2020 3:50:43 PM - 			Version : 
12/31/2020 3:50:43 PM - 
12/31/2020 3:50:43 PM - 	References         : 
12/31/2020 3:50:43 PM - Signature Details...
12/31/2020 3:50:43 PM - 	Extension is not signed.
12/31/2020 3:50:43 PM - 
12/31/2020 3:50:43 PM - Searching for applicable products...
12/31/2020 3:50:43 PM - Found installed product - Global Location
12/31/2020 3:50:43 PM - Found installed product - Visual Studio Community 2019
12/31/2020 3:50:43 PM - VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by herbix** [comment]
> 12/31/2020 3:50:43 PM - VSIXInstaller.NoApplicableSKUsException: **One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.**

It's for Visual Studio Code, please install it from here:

![image](https://user-images.githubusercontent.com/7110965/103433146-d8851280-4c26-11eb-8d62-e8a7e98abb13.png)

Or search it from extension list in VSC:

![image](https://user-images.githubusercontent.com/7110965/103433149-ecc90f80-4c26-11eb-98d7-1a4b19e7b728.png)
