### ISSUE TITLE
[Feature Request] Set root folder

### ISSUE THREAD

**Issue by Makkkkus** [herbix/hoi4modutilities#26]
A setting to set the root folder of the project. This is useful if you work in the /mod/ folder instead of the folder of the mod you are creating. I specifically request this because loading of the files from the gfx file is dependent on the folder you are in, which in my case is: mod, but the mod root is in mod/[modname], so files are loaded relative to mod instead of [modname]. Which causes it not not find the graphics in the gfx file.

GFX is located: mod/[modname]/gfx/test/test.dds, but the extension tries to load from mod/gfx/test/test.dds.

![image](https://user-images.githubusercontent.com/37084190/111066586-0789f100-84c0-11eb-910d-6f8e0283defc.png)

**Comment by herbix** [comment]
Hi, you can create a workspace that contains mod folder and other folders. The extension will read from all folders in the workspace.

**Comment by Makkkkus** [comment]
I will try
