### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by NitroMHGaming** [herbix/hoi4modutilities#3]
I followed the instructions to set it up but found it confusing. Could someone help please

**Comment by herbix** [comment]
Hi @NitroMHGaming. Could you please write some details about the confusing part?

**Comment by NitroMHGaming** [comment]
I couldn't find the Preview HOI4 File button. 
I changed the settings to this but i don't know if i did it correctly.
![C1](https://user-images.githubusercontent.com/52544678/85730363-82706900-b6f1-11ea-9078-a0e8883cc2dc.PNG)

**Comment by herbix** [comment]
I believe the paths are correct. There might be several reasons the button doesn't show up.
1. The extension is not enabled.
2. A mod folder that has same structure as game directory must be opened in VSCode. [Details about mod structure](https://hoi4.paradoxwikis.com/Mod_structure).
3. Only national focus (in `common/national_focus`), technologies (in `common/technologies`), gfx files (file name ends with `.gfx`) and `map/default.map` can be previewed. The file should be opened. The button will show up on right-top corner of the editor.
![image](https://user-images.githubusercontent.com/7110965/85742596-f5033800-b735-11ea-9db3-a1ddc7e52212.png)
