### ISSUE TITLE
[Feature request] Tag Colouring

### ISSUE THREAD

**Issue by BrannVonManner** [herbix/hoi4modutilities#31]
Could you possibly make it so the map determines country colours based on the RGB code associated with each country in the files so that tags not from the base game have colour on the map? If this is already a feature in some way, could you inform me how to use it?

**Comment by BrannVonManner** [comment]
It still is not working, are there any other files it relies on?

**Comment by herbix** [comment]
Did you add a file to `common/country_tags/` to map your country tag to country file in `common/countries/`?
![image](https://user-images.githubusercontent.com/7110965/117474155-3cc93180-af8d-11eb-8bbd-eae75935c3ba.png)

**Comment by BrannVonManner** [comment]
Thanks! My friend was the one who added the nations for the mod and had it referencing the wrong country folder (the one under history)
