### ISSUE TITLE
[BUG] Extension doesn't support meta_effects

### ISSUE THREAD

**Issue by Makkkkus** [herbix/hoi4modutilities#40]
**Describe the bug**
When opening a focus tree with a meta_effect, the extension fails to load the tree.

**To Reproduce**
1. Add a meta_effect to a focus
2. Click on Preview HOI4 File

**Expected behavior**
The focus tree works in the game, and I therefore think that it should load. This can easily be fixed by ignoring meta_effects.

**Screenshots**
![image](https://user-images.githubusercontent.com/37084190/136042876-c1dcbc2a-8df0-4f5a-98fa-3a6baad43f80.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - VSCode version: 1.60.2
 - Extension version: 0.4.6

**Console Logs**
![image](https://user-images.githubusercontent.com/37084190/136043293-d9714948-aaac-461e-acc5-4e3d4ac62da3.png)

Thank you!

**Comment by herbix** [comment]
Hi @Makkkkus 
Thanks for reporting the issue.
Could you please provide a snippet that contains meta_effect and triggered the issue? I checked official document of meta_effect but didn't find anything that breaks the parser.

**Comment by Makkkkus** [comment]
Okay, here it is:

	completion_reward = {
		hidden_effect = {
			meta_effect = {
				text = {
					set_country_flag = [META_SET_RULING_PARTY]
				}
				META_SET_RULING_PARTY = "[meta_set_ruling_leader]"
			}
		}
	}

**Comment by herbix** [comment]
Fixed in v0.4.7.
