### ISSUE TITLE
[BUG] Right-click menu makes it harder to move the map

### ISSUE THREAD

**Issue by Makkkkus** [herbix/hoi4modutilities#41]
**Describe the bug**
If you open the map by clicking view map and you try moving around the map by right clicking, a right-click menu appears, which prevents you from moving the map around. Every time you want to move, you have to left-click to remove the menu, and then drag again.

**To Reproduce**
1. Press Ctrl-Shift-P
2. Search for Preview World Map
3. Move the map by right-clicking

**Expected behavior**
I don't expect the right-click menu to open.

**Screenshots**
![image](https://user-images.githubusercontent.com/37084190/137485121-398dcfa6-7698-4bbf-8407-fe0a9571c978.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, version 1903
 - VSCode version: 1.61.1
 - Extension version: 0.4.7

**Comment by herbix** [comment]
It seems that it's caused by VSCode update. Let me fix it.
