### ISSUE TITLE
[BUG] Preview event localisation

### ISSUE THREAD

**Issue by gyhs** [herbix/hoi4modutilities#42]
**Describe the bug**
I added event loc value (mod), but I can't check mod's localisation

**To Reproduce**
1. Go to your mod and open custom event
2. Click on Preview HOI4 File
3. add "#!localisation:localisation/im_localisation_l_english.yml"

**Expected behavior**
this option is for only vanila.

**Screenshots**

![error](https://cdn.discordapp.com/attachments/726411271100170290/905927595420430336/unknown.png)

**Comment by herbix** [comment]
@gyhs 
In events, localization key is `title` field of `country_event`, which is from [official wiki](https://hoi4.paradoxwikis.com/Event_modding#title). Did you miss `title` field? If it does work without `title` in game, please let me know. I'll update the extension to support it.
![image](https://user-images.githubusercontent.com/7110965/140443374-dbaed952-7654-4f1c-8837-22526a5765d8.png)
![image](https://user-images.githubusercontent.com/7110965/140443454-05722b04-3786-4637-815f-557da44301f7.png)

**Comment by gyhs** [comment]
@herbix 
![image](https://user-images.githubusercontent.com/42140432/140453915-2467dff9-501f-45c9-af23-343421d31b8a.png)
![image](https://user-images.githubusercontent.com/42140432/140454148-72bd8f18-3f66-48c4-bae9-53266fc4bb2d.png)

sadly, I wrote it...
I think ext is something wrong

**Comment by herbix** [comment]
@gyhs
Another possible reason is that your localization file is not in correct YAML format. You can open developer tools with command `Developer: Toggle Developer Tools` and navigate to console tab to check whether there's a `YAMLException`.
![image](https://user-images.githubusercontent.com/7110965/140489602-3e8889b2-6ad1-4129-bcdb-514eb40314b5.png)

**Comment by herbix** [comment]
BTW, vanilla HOI4 localization files are not in correct YAML format too.
The number after colon is not supported by YAML format. I'm not sure why it's here. But I did some trick to remove them all. Maybe there're some rules in localization files that I didn't care about.
> FEN_heavy_fighter_equipment_3_short:**0** "PF-98"

**Comment by gyhs** [comment]
![image](https://user-images.githubusercontent.com/42140432/140491398-65956ac5-6728-47d5-951b-82f28d155f94.png)
I thank you very much, 
![image](https://user-images.githubusercontent.com/42140432/140491511-27da0580-3af6-4672-b0fb-c72e827775e1.png)
fixed every lines!
but can you support :0 < this format?

**Comment by gyhs** [comment]
@herbix 
![image](https://user-images.githubusercontent.com/42140432/140491702-86eccb82-d5a4-499f-99bb-ca462c75a192.png)
ah, and what is this? why can't use korean translation file?

**Comment by herbix** [comment]
> but can you support :0 < this format?

Actually it's supported. I guess there're other format issues that triggered this bug.

> why can't use korean translation file?

The extension tries to load translation file from your vscode language configuration, but Korean translation file is not supported by my extension yet. It will fall back to English.

**Comment by gyhs** [comment]
Ah, i see! Thank you for your advices!
