### ISSUE TITLE
[Feature request] new map modes for new update

### ISSUE THREAD

**Issue by SoloWinPixy** [herbix/hoi4modutilities#43]
change the old supply view mode into the new one so it displays railways and supply nodes?

**Comment by herbix** [comment]
Oh, you remind me. I forgot to check changes from the new DLC.

**Comment by SoloWinPixy** [comment]
yea, they got rid of supply areas now

**Comment by SoloWinPixy** [comment]
now its just supply

**Comment by herbix** [comment]
Added support in version 0.5.0.
