### ISSUE TITLE
[BUG] No support ext in Web VS Code

### ISSUE THREAD

**Issue by Sepera-okeq** [herbix/hoi4modutilities#47]
Hi! Can you implement support for the web version of the extension for VS Code?

![image](https://user-images.githubusercontent.com/54331959/156863182-57cd7826-40a4-4ebb-ab3f-27d4e3fad9ac.png)

**Comment by herbix** [comment]
This extension needs to read local file. I'll check whether this can work with a web version VS code.

**Comment by herbix** [comment]
Supported in v0.7.0.
