### ISSUE TITLE
[BUG] Rail visualiser doesn't work if the lines are tabbed in

### ISSUE THREAD

**Issue by Hola-Man** [herbix/hoi4modutilities#49]
**Describe the bug**
The world map previewer doesn't strip leading tabs/spaces

**To Reproduce**
1. Tab in a line in the railway file
2. open the world map previewer
3. See error

**Expected behavior**
The program should strip the tabs before reading the rail lines, and yet it does not
many of these rails are going to provinces with ids that are actually used in the file to represent length - province 9 is the very popular one off of south america

**Screenshots**
![gunknown](https://user-images.githubusercontent.com/81699699/173193049-d16b7c2d-03e9-4092-8096-f686c495cda8.png)

**Desktop (please complete the following information):**
 - OS: idk it wasn't me who took the screenshot
 - VSCode version: idk
 - Extension version: idk

**Comment by herbix** [comment]
Fixed in https://github.com/herbix/hoi4modutilities/commit/31efcd6d928a08e032c30dca32e76be1e087664b.
