### ISSUE TITLE
[BUG] Selected focus condition gets reset when re-rendered.

### ISSUE THREAD

**Issue by AndreasBrostrom** [herbix/hoi4modutilities#52]
**Describe the bug**
When selecting a set of conditions for the focus tree previewer it get reset when the the tree re-renders.

**To Reproduce**
1. Open up a focus tree vanilla or modded
2. Make sure you can use focus tree conditions (ie. not disabled useConditionInFocus)
3. Select a condition set
4. Edit the three
5. Selection is reset

**Expected behavior**
The selection to be kept even if the tree is re-rendered.

**Screenshots**
![image](https://user-images.githubusercontent.com/38365066/181236081-24bf5610-901a-4b37-9b00-813e9715c671.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - VSCode version: 1.69.2
 - Extension version: v0.5.2

**Console Logs**
N/A

**Comment by herbix** [comment]
Fixed in https://github.com/herbix/hoi4modutilities/commit/485d83281f8597fdaddc9518549bde9e780c2c99.
