### ISSUE TITLE
[BUG] Cant find tech folder for any doctrine sinse it have moved

### ISSUE THREAD

**Issue by AndreasBrostrom** [herbix/hoi4modutilities#53]
**Describe the bug**
PDX have since the changes to techtrees and how doctrines work. The doctrine tech now a own treeview.gui file  `interface\countrydoctrinetreeview.gui` instead of `interface\countrytechtreeview.gui`

This now causes issue with the previewer no never finding the tech folder.
![image](https://user-images.githubusercontent.com/13811113/182014124-1f0d6760-c7ae-4b1c-93dd-dd8992d9c16a.png)

**To Reproduce**
1. Open a land navy or air doctrine tech file.
2. Click on the preview button
3. See error

**Expected behavior**
To be able to show the techtree

**Screenshots**
![image](https://user-images.githubusercontent.com/13811113/182014189-980e3b57-23bb-406d-b34e-ba6283e18530.png)

**Desktop (please complete the following information):**
- OS: Win11
- VSCode version: 1.69.2
- Extension version: v0.5.2

**Console Logs**
N/A

**Comment by AndreasBrostrom** [comment]
Attempted hack solution seams not to work out of the box so it seams it needs some more fiddeling.
Attempt below:
`Or = ["interface/countrytechtreeview.gfx", "interface/countrytechnologyview.gfx", "interface/technologies.gfx"];`
to 
`Or = ["interface/countrytechtreeview.gfx", "interface/countrytechnologyview.gfx", "interface/technologies.gfx", "interface/countrydoctrinetreeview.gui"];`

**Comment by herbix** [comment]
I didn't realize that doctrine was moved to another file. Currently the file name was hard coded. Let me find a way to fix it.

**Comment by herbix** [comment]
Fixed in https://github.com/herbix/hoi4modutilities/commit/140f93f7cc92a0e5dbafd2aea8aa416599da18f1.
