### ISSUE TITLE
[Feature request] .PNG Support of Focus Icon Preview

### ISSUE THREAD

**Issue by TheFunkymenStudio** [herbix/hoi4modutilities#54]
**Is your feature request related to a problem? Please describe.**
For the bigger mods, PNG is often use for icons as the format is more optimized than DDS, however the format is not actually supported by this very useful extension.
Could it be possible to add this format ?

**Comment by herbix** [comment]
.png is supported in focus preview.
You may need to add the .gfx as a dependency to load it in preview: https://github.com/herbix/hoi4modutilities/wiki/Reference-custom-sprite_type
