### ISSUE TITLE
[Question]How to use highlighting

### ISSUE THREAD

**Issue by Buritsuchidasuto** [herbix/hoi4modutilities#55]
I noticed that it can highlight in you provided demos to this tool. but, I can't find out how to use it and it's very necessary and important for me. So, I must ask for your help even though I hate to trouble you. 

Thanks a lot.

桥头尘埃

**Comment by herbix** [comment]
Hi @Buritsuchidasuto, can you please provide detailed information about the question? I'm not sure which demo you were refer to. You can paste screenshot if needed.
