### ISSUE TITLE
[Question]Can't load mod

### ISSUE THREAD

**Issue by swedishdonkey** [herbix/hoi4modutilities#58]
I wan't to load the map I made but it is still the original one.
 Is it the path problem? Or the mod file.
The description said it will read the replace_path. But I can't find replace_path in both of the .mod file.
![屏幕截图 2023-03-10 002641](https://user-images.githubusercontent.com/127428032/224089791-8086dfe9-5b11-499b-ad25-955dd3cd16f6.png)
![屏幕截图 2023-03-10 002720](https://user-images.githubusercontent.com/127428032/224089811-9fde4870-57b6-4f0d-a810-c53267b803b7.png)
![屏幕截图 2023-03-10 004124](https://user-images.githubusercontent.com/127428032/224092347-2477253e-6206-43da-a77a-865fac4d53fd.png)
![屏幕截图 2023-03-10 002800](https://user-images.githubusercontent.com/127428032/224089830-a9083959-e3c7-4b86-b503-d5e7227bfd1b.png)

**Comment by herbix** [comment]
你需要用vscode的“打开目录”功能打开你的mod目录，和replace_path的设置没有关系。
