### ISSUE TITLE
Colorcoding

### ISSUE THREAD

**Issue by LeiteArts10** [herbix/hoi4modutilities#6]
Hello, I looked on your previews that you have variables colorcoded in the VSC editor (strings in orange, numbers in green, etc), can you share those settings with us?

Currently mine are all white as you can see in the picture bellow

![example](https://user-images.githubusercontent.com/7028327/89331363-05c59880-d668-11ea-8552-97a3a52b14bf.png)

**Comment by herbix** [comment]
Hi @LeiteArts10,

I uses CWTools for syntax highlighting. Please check this extension:

![image](https://user-images.githubusercontent.com/7110965/89373186-9a88ce80-d71a-11ea-8685-fb852ddaf183.png)
