### ISSUE TITLE
[BUG]Preview is not showing images if in dlc folder.

### ISSUE THREAD

**Issue by Mefisto1029** [herbix/hoi4modutilities#60]
**Describe the bug**
Images are not shown if they are in dlc folder.

**To Reproduce**
1. Go to 'dlc000_xxx'
2. Open on 'any_file.gfx'
3. Turn on preview

**Expected behavior**
All images should be shown.

**Screenshots**
![VSC](https://user-images.githubusercontent.com/128325543/236627089-6ded233c-6a61-4d46-a5b3-b71d68d1d302.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - VSCode version: 1.70.3
 - Extension version: v0.5.2

**Comment by herbix** [comment]
Fixed in https://github.com/herbix/hoi4modutilities/commit/25b4a46437b251a17941ca29cd05764afbff4b8b .
