### ISSUE TITLE
Preview button disappeared or not working.

### ISSUE THREAD

**Issue by Mefisto1029** [herbix/hoi4modutilities#61]
**Describe the bug**
Preview button disappeared in NF and Tech trees, plus it's stopped working in gfx files.

Workstation is not as mod or in game files but in separate folder in desktop. Tho it's wasn't problem in v0.5.2

**To Reproduce**
1. Just try to open preview.

**Expected behavior**
Button should work.

**Screenshots**
NF tree
![NF](https://github.com/herbix/hoi4modutilities/assets/128325543/54a6cfa8-aa34-478f-8975-e8e0b176c3ff)
GFX
![gfx](https://github.com/herbix/hoi4modutilities/assets/128325543/62245fa7-1c30-41f7-88a2-628b2675427f)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - VSCode version: 1.70.3
 - Extension version: v0.6.1, v0.6.0 (Happen in both)

**Comment by herbix** [comment]
I can't repro the issue. Before I found the cause, you can install the old version here:

![image](https://github.com/herbix/hoi4modutilities/assets/7110965/8e66af1f-62ec-4031-b069-a91540b2fbaa)
[hoi4modutilities-0.5.2.zip](https://github.com/herbix/hoi4modutilities/files/11432468/hoi4modutilities-0.5.2.zip)

**Comment by Mefisto1029** [comment]
Ok in v0.6.2 it works. Thank you.
