### ISSUE TITLE
Not seeing entire focus tree

### ISSUE THREAD

**Issue by Caettus** [herbix/hoi4modutilities#63]
![image](https://github.com/herbix/hoi4modutilities/assets/57236558/5f5df08a-3287-4c35-9eb1-71e4bae849b2)

In the image you can see that I have the normal germany focus tree open, but I am not able to preview the entire focus tree. Only a part of it, this is the same with other focus trees

**Comment by herbix** [comment]
Can you please try toggle conditions?
Some focuses are only visible on certain conditions.

**Comment by herbix** [comment]
It was because conditions weren't evaluated correctly.
Fixed in v0.7.1.
