### ISSUE TITLE
[BUG] Part of tree is invisible if prerequisite is empty.

### ISSUE THREAD

**Issue by Mefisto1029** [herbix/hoi4modutilities#64]
**Describe the bug**
Part of tree is invisible if prerequisite is in focus but is empty.

**To Reproduce**

1. See "FRA_devalue_the_franc" in French tree.

**Expected behavior**
Even with empty prerequisites bracket, focus tree should be visible.

**Screenshots**
With empty prerequisites
![prereq](https://github.com/herbix/hoi4modutilities/assets/128325543/c0302ab2-49c3-446f-b02c-c90e31ad22be)
Without prerequisites
![no prereq](https://github.com/herbix/hoi4modutilities/assets/128325543/7a2dddb3-247f-4402-8b1a-d7f9fc0946da)

**Desktop (please complete the following information):**

- OS: Windows 7
- VSCode version: 1.70.3
- Extension version: v0.7.1

**Comment by herbix** [comment]
Fixed in 0.7.3
