### ISSUE TITLE
[BUG] Part of tree visible even if it shouldn't.

### ISSUE THREAD

**Issue by Mefisto1029** [herbix/hoi4modutilities#65]
**Describe the bug**
Focuses which require dlc are visible even if condition is not met.

**To Reproduce**

1. See Polish tree

**Expected behavior**
Tree blocked with allow_branch should be invisible if none of conditions is set.

**Screenshots**
![All visible](https://github.com/herbix/hoi4modutilities/assets/128325543/284714b2-a254-4029-bae3-ae5d104c30c3)

**Desktop (please complete the following information):**

- OS: Windows 7
- VSCode version: 1.70.3
- Extension version: v0.7.1

**Note:**
It might be because double allow_branch in focus.
![merged](https://github.com/herbix/hoi4modutilities/assets/128325543/f6301a51-afdd-4239-b4f3-edc2352bb2f7)

**Comment by herbix** [comment]
Fixed in 0.7.3.
