### ISSUE TITLE
[Question] When is next update?

### ISSUE THREAD

**Issue by gyhs** [herbix/hoi4modutilities#69]
Just curious & To check my translation is correct

**Comment by herbix** [comment]
You may download the VSIX here and install manually on your computer: https://github.com/herbix/hoi4modutilities/actions/runs/5577064174
![image](https://github.com/herbix/hoi4modutilities/assets/7110965/1f92eccd-e075-4217-9a25-cf80d8844398)

Each time you create a PR or update a PR, an action run will be generated. You can get the VSIX before updating the extension on marketplace.

**Comment by gyhs** [comment]
Woo, it's cool, thanks!
