### ISSUE TITLE
Error loading webview

### ISSUE THREAD

**Issue by BrammekeTV** [herbix/hoi4modutilities#72]
![Screenshot_1](https://github.com/herbix/hoi4modutilities/assets/39600787/d667090c-1342-44a4-ac99-3e9ad591998f)
Getting this error when trying to preview anything

**Comment by herbix** [comment]
This seems to be a common issue of VSCode. Here's a possible solution I found:
https://stackoverflow.com/questions/67698176/error-loading-webview-error-could-not-register-service-workers-typeerror-fai

In short. You can try update and restart vscode, and restart computer.
