### ISSUE TITLE
An Error

### ISSUE THREAD

**Issue by cabbagefavor** [herbix/hoi4modutilities#73]
Hello, I'd like you to deal with an error.
Since the Simplified Chinese update, the localization key values in "simp_chinese.yml" have been written, but they will report an error in "event.txt" that there is no localized value.
Thank you！

**Comment by cabbagefavor** [comment]
By the way, some of these errors are in vscode. The localization key value has been written, but in many places there are errors that do not have a localization value. These localized keys are written in simplified Chinese.

**Comment by herbix** [comment]
Currently only English localisation is supported. Please add .yml for English, too.

**Comment by herbix** [comment]
Added a setting in 0.9.0 to set language of event preview.
