### ISSUE TITLE
[BUG]If focus have multiple icons, preview do not show any of them.

### ISSUE THREAD

**Issue by Mefisto1029** [herbix/hoi4modutilities#75]
**Describe the bug**
As title.

**To Reproduce**
Open norwegian focus tree preview.
Look at NOR_a_new_norway

**Expected behavior**
At least one of icons should be visible

**Screenshots**
![No icon](https://github.com/herbix/hoi4modutilities/assets/128325543/dc220e72-8dd7-4cea-9f20-865ce3938de6)

**Fix suggestion**
If icon is block instead of value, look in each icon and take one where there is no trigger block, if all icons have trigger block take first from top.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - VSCode version: 1.70.3
 - Extension version: v0.7.4

**Comment by herbix** [comment]
This is a feature from new version of HOI4. I haven't got a chance to implement it. Same for #76.

**Comment by herbix** [comment]
Fixed in 0.8.0.
