### ISSUE TITLE
[BUG]Joint focus tree preview do not work.

### ISSUE THREAD

**Issue by Mefisto1029** [herbix/hoi4modutilities#76]
**Describe the bug**
As title.

**To Reproduce**
Open nordic_shared focus tree preview

**Expected behavior**
Focuses should be visible in preview

**Screenshots**
![nordic](https://github.com/herbix/hoi4modutilities/assets/128325543/dd1676ac-faf3-45b5-8f98-c55b85203a47)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - VSCode version: 1.70.3
 - Extension version: v0.7.4

**Comment by herbix** [comment]
Fixed in 0.8.0.
