### ISSUE TITLE
[改进] 国策树预览使用本地化名称替换国策Id

### ISSUE THREAD

**Issue by textGamex** [herbix/hoi4modutilities#82]

**Comment by ArkhalisDragon** [comment]
快一年了这个功能还没上....

**Comment by IShiraiKurokoI** [comment]
> 快一年了这个功能还没上....

已经有了啊，你featureflag里打开localisationIndex就有了啊
https://github.com/herbix/hoi4modutilities/wiki/Feature-flags

**Comment by ArkhalisDragon** [comment]
> > 快一年了这个功能还没上....
> 
> 已经有了啊，你featureflag里打开localisationIndex就有了啊 https://github.com/herbix/hoi4modutilities/wiki/Feature-flags

刚刚开了一下VSC看到有本地化索引加载完成的提示了，不过还是重启了一下VSC才看到本地化，感谢
