### ISSUE TITLE
map freeze

### ISSUE THREAD

**Issue by LeXus21251** [herbix/hoi4modutilities#83]
on 0.11 update my map freezes when choosing state view mode

**Comment by herbix** [comment]
Hi @LeXus21251, can you please check whether it's the same issue as #81?

**Comment by LeXus21251** [comment]
Yes it's the same issue, I'll try fix it on my own. Thanks for quick answer
Btw when 11.1 will be on VSC because its only 11.0 for me

**Comment by herbix** [comment]
I forgot to publish it. It's done now.aa
