### ISSUE TITLE
GFX support for mods as well as base game

### ISSUE THREAD

**Issue by Fullchord** [herbix/hoi4modutilities#92]
My focus tree preview does not work for GFX in the mod I am working on, but it does work for the GFX in the base game. 
![image](https://github.com/herbix/hoi4modutilities/assets/112035330/3899566f-5a46-4ac4-8095-fa6128b3b458)

**Comment by herbix** [comment]
Hi @Fullchord, can you please try adding `gfxIndex` in feature flags?
Here's the related wiki:
https://github.com/herbix/hoi4modutilities/wiki/Feature-flags#list-of-feature-flags

**Comment by Fullchord** [comment]
@herbix Yes, I enabled that setting with the same outcome as above. Here is my settings file
![image](https://github.com/herbix/hoi4modutilities/assets/112035330/85d7cd7c-3a24-4051-b1a5-588a8726c140)
Me and my friends have never gotten the in-mod focus tree gfx to work while the base game gfx does work

**Comment by gyhs** [comment]
https://github.com/herbix/hoi4modutilities/wiki/Reference-custom-sprite_type

check this page

**Comment by Fullchord** [comment]
@gyhs This fixed my issue. Thanks for the response.
