### ISSUE TITLE
[BUG] Removing traits from MIO does not remove them from the preview.

### ISSUE THREAD

**Issue by Mefisto1029** [herbix/hoi4modutilities#96]
**Describe the bug**
Removing traits from MIO does not remove them from the preview.

**Expected behavior**
Trait should be removed from preview.

**Screenshots**
![Bug](https://github.com/user-attachments/assets/76828a87-a483-42a8-85c0-a60fc2dbece3)

- Extension version: v0.12.0

**Comment by herbix** [comment]
Fixed in v0.12.1
