### ISSUE TITLE
Can't preview technology 

### ISSUE THREAD

**Issue by JustKaarlo** [herbix/hoi4modutilities#98]
Whenever i try to preview my technology file it says **Can't find technology folder bm_doctrine_1_folder in interface/countrytechtreeview.gui,interface/countrydoctrinetreeview.gui,** it worked fine in-game and before, and i have added all the code to **countrydoctrinetreeview.gui**. I don't understand what the problem can be.
![Screenshot 2024-09-11 200814](https://github.com/user-attachments/assets/e8810cc3-77ea-4558-a43d-cd8bfa362d04)

**Comment by herbix** [comment]
Hi @JustKaarlo, can you please share the code of countrydoctrinetreeview.gui and bm_doctrine_1.txt? Then I'll try to repro this bug on my machine.

**Comment by JustKaarlo** [comment]
[countrydoctrineview.txt](https://github.com/user-attachments/files/16979594/countrydoctrineview.txt)
[bm_doctrine_1.txt](https://github.com/user-attachments/files/16979597/bm_doctrine_1.txt)
[bm_doctrine_2.txt](https://github.com/user-attachments/files/16979602/bm_doctrine_2.txt)
[bm_doctrine_3.txt](https://github.com/user-attachments/files/16979604/bm_doctrine_3.txt)
[BM_technology.txt](https://github.com/user-attachments/files/16979600/BM_technology.txt)
There you go!

**Comment by IShiraiKurokoI** [comment]
> [countrydoctrineview.txt](https://github.com/user-attachments/files/16979594/countrydoctrineview.txt) [bm_doctrine_1.txt](https://github.com/user-attachments/files/16979597/bm_doctrine_1.txt) [bm_doctrine_2.txt](https://github.com/user-attachments/files/16979602/bm_doctrine_2.txt) [bm_doctrine_3.txt](https://github.com/user-attachments/files/16979604/bm_doctrine_3.txt) [BM_technology.txt](https://github.com/user-attachments/files/16979600/BM_technology.txt) There you go!

Hi @JustKaarlo Maybe you accidentally wrote the file name `countrydoctrineview.txt` instead of `countrydoctrinetreeview.gui`. The vanilla Hearts of Iron 4 does not have a gui file called the `countrydoctrineview.txt`, so this file won't be looked up when rendering the tech tree preview.

![image](https://github.com/user-attachments/assets/2421036e-5392-48e0-b082-ff938e298bf0)

![image](https://github.com/user-attachments/assets/10e6f521-bc6a-4f9d-bbb1-d081dfc75ef6)

![image](https://github.com/user-attachments/assets/79222f38-b60e-40fe-8243-34ac30b000be)

**Comment by JustKaarlo** [comment]
> Hi @JustKaarlo Maybe you accidentally wrote the file name `countrydoctrineview.txt` instead...

Nope, its named the right why
![Screenshot 2024-09-12 204848](https://github.com/user-attachments/assets/4eb93fb6-85b1-46ca-84e2-7964f060c43b)
I guess its not your extension that causing the problem maybe its something with my vscode. If it is how do i find the problem?

**Comment by JustKaarlo** [comment]
Looks like its working again have no clue how it started working it just started working from no where.

**Comment by JustKaarlo** [comment]
It seems to be working again, though I have no idea how. At least it's functioning now, but I’m not sure what I did to fix it.
